# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Hand That Rocks The Gradle
description: > # this means to ignore newlines until "baseurl:"
  Hear the tales of the old school I.T. guy as he fumbles his way though learning how to be a Developer!
  Wonder at the foibles and follies as he moves from knowing how to script to understanding Object Oriented languages!
  See him reprogram his brain from LAMP to Champ!
  Seriously what have I gotten myself into?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: GradleRocker
github_username:  TheHandThatRocksTheGradle

# Build settings
markdown: kramdown
