title: The Hand That Rocks The Gradle
description: > # this means to ignore newlines until "baseurl:"
  Hear the tales of the old school I.T. guy as he fumbles his way though learning how to be a Developer!
  Wonder at the foibles and follies as he moves from knowing how to script to understanding Object Oriented languages!
  See him reprogram his brain from LAMP to Champ!
  Seriously what have I gotten myself into?
author: TheHandThatRocksTheGradle
logo: /static/img/Logo.png
github: https://github.com/TheHandThatRocksTheGradle
about: Budding developer
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Resume
      url: '#'
      icon: fa-graduation-cap
    - text: Github
      url: https://github.com/TheHandThatRocksTheGradle
      icon: fa-github
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed
      target: _blank

social:
    - icon: fa-facebook
      link: '#'
    - icon: fa-skype
      link: '#'
    - icon: fa-twitter
      link: '#'
    - icon: fa-linkedin
      link: '#'
    - icon: fa-stack-exchange
      link: '#'

share:
  twitter_username: 'GradleRocker'
  fb_appid: 000000000000


enableTags: true
tagarray: []

#url: "http://aboutashu.com/hcz-jekyll-blog"
#baseurl: "/hcz-jekyll-blog"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
